title: Neural Fields Reading Group
url: "https://github.com/Neural-Fields-Reading-Group/neural-fields-reading-group.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Neural Fields Reading Group is maintained by <a href='https://github.com/maurock'>maurock</a>. Theme by <a href='https://github.com/ankitsultana/researcher'>researcher</a>" 

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"